dbfound:
  system:
    model-modify-check: true
  web:
    open-session: false
  datasource:
    db0:
      url: jdbc:mysql://127.0.0.1:3306/dbfound?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: dbfound
      password: dbfound
      dialect: MySqlDialect
spring:
  jackson:
    property-naming-strategy: SNAKE_CASE