dbfound:
  system:
    underscore-to-camel-case: false
    open-log: true
    model-modify-check: true
  web:
    open-session: false
  datasource:
    db0:
      url: jdbc:mysql://192.168.1.111:3306/dbfound?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
      driver-class-name: com.mysql.cj.jdbc.Driver
      username:
      password:
      dialect: MySqlDialect
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8